#! /usr/bin/env python3
#  coding:utf8


# UDPServer

import socket

s = socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
s.bind = (('127.0.0.1',9999))
print ('Bind UDP on 9999...')
while True:
	data,addr = s.recvfrom(1024)
	print ('Received from %s:%S.' % addr)
	s.sendto(b'Hello,%s' % data,addr)


# UDPClient

import socket

s = socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
for data in [b'Hello',b'World']:
	s.sendto(data,('127.0.0.1',9999))
	print (s.recv(1024).decode('utf-8'))
s.close()
